### ISSUE TITLE
Experiencing difficulties when attempting to detach tabs.

### ISSUE THREAD

**Issue by oo7Bis** [soulhotel/Perfection-Firefox-CSS-Theme#2]
When attempting to detach a tab and create a new window in Firefox, I encounter an issue. Unlike the standard behavior, dragging the tab on top of the Firefox window doesn’t work as expected. To detach the tab, I currently need to either minimize Firefox and drag the tab out of the browser or move it to another monitor where Firefox isn’t present.

**Comment by soulhotel** [comment]
Dont know if you solved it on your own, but this is handled in Sidebery Settings / Drag and Drop Section
